= Introduction

* Relevant https://lists.apache.org/thread.html/44d3a2dd8a6fb40baa0120acc88c9244404653706974fb422cb7d546@%3Cdev.knox.apache.org%3E[mailing list thread]

=== Out Of Scope

* Platforms other than Linux (e.g. Windows)
* Tools other than Knox CLI and the Gateway itself


= Maven Assemblies

Knox uses the Maven Assembly plugin to build various JAR files.
The important ones for us are:

* `knoxcli.jar`
** Main Class: `org.apache.knox.gateway.launcher.Launcher`
** Actual Main Class: `org.apache.knox.gateway.util.KnoxCLI`
** Maven Module: `knox-cli-launcher`
* `gateway.jar`
** Main Class: `org.apache.knox.gateway.launcher.Launcher`
** Actual Main Class: `org.apache.knox.gateway.GatewayServer`
** Maven Module: `gateway-server-launcher`

= Shell scripts

There is a bash script for each use-case:

* `knoxcli.sh`
* `gateway.sh`
* `knox-env.sh`
** Not called directly but sourced by the others

The CLI tools don't start the relevant classes (e.g. `GatewayServer`) directly but instead starts a `Launcher` class (see above) which runs some bootstrapping code and then starts the relevant main class later.


== gateway.sh

1. Sources `knox-env.sh`
1. It checks whether various directories are readable and/or writable
1. It runs Java with various parameters which cannot be overridden.

WARNING: A Problem here is that the `gateway.sh` script uses a different way of resolving directories than the Java code. So it can fail startup even if the Java code would work.

We can not resolve this problem when directories can be configured using `gateway-site.xml`.
Environment variables and Java properties we could control because we're the script that passes them in but `gateway-site.xml` is not under our control.


== knoxcli.sh

This works very similar to `gateway.sh` with fewer options so I'd apply the same changes here.


== Proposed changes

1. https://github.com/anordal/shellharden[shellharden] & https://github.com/koalaman/shellcheck[shellcheck]
1. Stop redirecting stderr & stdout to a file when the server runs in the foreground
1. Introduce environment variables with a prefix of KNOX_GATEWAY_ that allow changing the internal ones
** e.g. `KNOX_GATEWAY_LOG_OPTS`
1. Remove the hardcoded checks for directory existence (TODO: Remove or fix if possible?)
1. Move the function from `knox-env.sh` to `knox-functions.sh`
1. Remove the empty `ENV_PID_DIR` from `knox-env.sh`
* Emit a warning first if it's set outside
1. Document all possible environment variables in `knox-env.sh` but leave them commented
1. Entirely remove the checks for readability & writability of directories


TODO: Not sure if it would also make sense to search for `knox-env.sh` in a different location (e.g. config dir)


= Java

== Launcher

1. Finds the directory where its own JAR is located
1. Calculates a "launcher name" which is based on the JAR file that's loaded (e.g. gateway.jar -> gateway)
** These jar files are also located in the `bin` directory right next to the shell scripts
1. It loads a Properties file called `launcher.cfg` file from the classpath (`META-INF/launcher.cfg`)
** This default property file contains four properties:
*** GATEWAY_HOME -> ${launcher.dir}/..
*** log4j.configuration -> "${GATEWAY_HOME}/conf/${launcher.name}-log4j.properties
*** main.class -> org.apache.knox.gateway.GatewayServer
*** class.path `../conf;../lib/\*.jar;../dep/*.jar;../ext;../ext/*.jar`
1. It reads two variables from this embedded file called "override" and "extract"
** These are not present in the `launcher.cfg` for the Gateway or the KnoxCLI so they always default to `true`
1. If `override` is true Launcher now tries to find and/or create a file called `${launcher name}.cfg` in the launcher jar directory
** If it can't find this file it'll create a copy of its internal one
1. It'll set the properties `launcher.dir` (e.g. the `bin` dir) and `launcher.name` (e.g. `gateway`)
1. Launcher then calls `Command` with the properties (now six by default) it just created

== Command



== Gateway Home Dir

TODO

== Data Dir

1. Java Property: TODO
2. Environment Variable
3. Configuration Property `gateway.data.dir`
4. Default: `${gateway home}/data`


=== Services Dir

1. Configuration Property: `gateway.services.dir`
2. Default: `${data dir}/services`


=== Applications Dir

1. Configuration Property: `gateway.applications.dir`
2. Default: `${data dir}/applications`


=== Deployment Dir

1. Configuration Property: `gateway.deployment.dir`
2. Default: `${data dir}/deployments`


== Conf Dir

TODO: No Java Propertyy?
1. Configuration Property: TODO
2. Default: `${gateway home}/conf`

=== Shared Providers Config Dir

1. Default: `${conf dir}/shared-providers`


=== Descriptors Dir

1. Default: `${conf dir}/descriptors`


=== Topologies Dir

1. Default: `${conf dir}/topologies`


== Log Dir

1. Java Property: `log4j.configuration`


Knox uses the `PropertyConfigurator` to initialize Log4J.

If that is not defined it uses a default from its embedded `gateway.cfg` file which points to `${GATEWAY_HOME}/conf/${launcher.name}-log4j.properties`.
For this CSD we've modified the `gateway.sh` script to take an extra environment variable called `GATEWAY_LOG_OPTS` which we then point at the right location.


== Implementation notes

=== Changing the path where Knox looks for gateway-log4j.properties

Knox uses the `PropertyConfigurator` to initialize Log4J using the Java system property `log4j.configuration`.
If that is not defined it uses a default from its embedded `gateway.cfg` file which points to `${GATEWAY_HOME}/conf/${launcher.name}-log4j.properties`.
For this CSD we've modified the `gateway.sh` script to take an extra environment variable called `GATEWAY_LOG_OPTS` which we then point at the right location.

=== Changing the path where Knox looks for the gateway-site.xml file

Knox looks for `gateway-site.xml` in these locations in this order:

1. Java System Property `GATEWAY_HOME/conf/gateway-site.xml`
2. Environment variable `GATEWAY_HOME/conf/gateway-site.xml`
3. Java System Property `user.dir/conf/gateway-site.xml`
4. Classpath `conf/gateway-site.xml`

The path part `conf` is hardcoded.

Unfortunately the launcher has an embedded cfg file that contains a hardcoded `GATEWAY_HOME` property which the `Invoker` class then propagates to a Java System property.
The only way to have the environment variable take effect is by removing the default `conf/gateway-site.xml` file from the Knox distribution.
The directory `conf` needs to stay though because `gateway.sh` checks for its existence.
The path is hardcoded in the script and cannot be changed even though its pointing to the wrong location.
Solution is to create an empty `conf` directory or to patch the `gateway.sh` file.
This parcel does the former.